### ISSUE TITLE
How to use the bundle output in a docker container for production

### ISSUE THREAD

**Issue by OceanManOne** [python-poetry/poetry-plugin-bundle#39]
Hi

I'm in a search for a way to build a package for my monorepo project including the internal packages. This plugin seems like it is exactly what I need but I'm encountering an issue when trying to use the build output.

Trying to run the activate script of poetry inside the dockerfile, running:
. venv/bin/activate

It seems to activate the virtual environment but it doesn't find the python packages in projects.
Running python -m site inside the virtual environment results in:
(build) root@69ec21d33c0d:/app# python -m site
sys.path = [
    '/app',
    '/usr/local/lib/python38.zip',
    '/usr/local/lib/python3.8',
    '/usr/local/lib/python3.8/lib-dynload',
    '/usr/local/lib/python3.8/site-packages',
]
USER_BASE: '/root/.local' (doesn't exist)
USER_SITE: '/root/.local/lib/python3.8/site-packages' (doesn't exist)
ENABLE_USER_SITE: True

Which isn't the correct site-packages path.

What is the correct way using this plugin out with docker container?

**Comment by neersighted** [comment]
You can't activate a virtual environment in a Dockerfile using `source` or `.`. This is because those commands only work for a single shell session, and each `RUN` line represents a new shell session.

Set the `VIRTUAL_ENV` and `PATH` variables and things will work as you expect, e.g.

`ENV VIRTUAL_ENV=/path/to/env PATH=/path/to/env/bin:$PATH`
