### ISSUE TITLE
Bundle doesn't add all the internal packages

### ISSUE THREAD

**Issue by OceanManOne** [python-poetry/poetry-plugin-bundle#40]
Hi
I've encountered an issue where when using the plugin it does work with internal packages (packages I import as: lib1 = {path = "../../../poetry/lib1", develop = true} for example).

The issue is that when lib1 himself is importing another internal package, for example:
lib2 = {path = "../lib2", develop = true}

the output bundle doesn't contain lib2.
So it seems the plugin only works on the first level of internal packages, is it possible to add the ability to bundle all the project packages?

**Comment by neersighted** [comment]
It's possible there's a bug here, I'd like to see a minimal reproducer so we can be sure you're not running into a docs issue/misusage (or was possibly solved by python-poetry/poetry-core#512). That being said, keep in mind that Poetry projects/Python packages are not trees. A path dependency doesn't leak more information than a PEP 508 marker (so, `lib2 @ file://path/to/lib2`), and we have not yet come up with a plan or decided on if we want to break that veil for 'monorepo' support.

In any case, please provide a reproduction so that we can figure out what is going on/what is expected.

**Comment by OceanManOne** [comment]
I've retried it on a complete new setup and wasn't able to reproduce as everything seems to work as expected.
